server:
  port: 6063

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sea
      database: sea


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.order_service.serializer.OrderSerializer
      properties:
        spring.json.type.mapping: "order:com.order_service.entities.Order"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka