server:
  port: 6060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sea
    username: postgres
    password: aditya(2003)


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.user_service.serializer.UserSerializer
      properties:
        spring.json.type.mapping: "user:com.user_service.entities.User"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka