server:
  port: 6064

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sea
    username: postgres
    password: aditya(2003)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: "order-consumer-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.order_consumer.deserializer.OrderDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: order:order_consumer.entities.Order


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka